
{{- if .Values.hub.metrics.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "jupyterhub.hub.name" . }}
  {{- if .Values.hub.metrics.serviceMonitor.namespace }}
  namespace: {{ .Values.hub.metrics.serviceMonitor.namespace }}
  {{- else }}
  namespace: {{ .Release.Namespace }}
  {{- end }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: hub
    {{- if .Values.hub.metrics.serviceMonitor.additionalLabels }}
    {{- include "common.tplvalues.render" (dict "value" .Values.hub.metrics.serviceMonitor.additionalLabels "context" $) | nindent 4 }}
    {{- end }}
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  endpoints:
    - port: http
      path: {{ .Values.hub.metrics.serviceMonitor.path }}
      {{- if .Values.hub.metrics.serviceMonitor.interval }}
      interval: {{ .Values.hub.metrics.serviceMonitor.interval }}
      {{- end }}
      {{- if .Values.hub.metrics.serviceMonitor.scrapeTimeout }}
      scrapeTimeout: {{ .Values.hub.metrics.serviceMonitor.scrapeTimeout }}
      {{- end }}
      {{- if .Values.hub.metrics.serviceMonitor.honorLabels }}
      honorLabels: {{ .Values.hub.metrics.serviceMonitor.honorLabels }}
      {{- end }}
      {{- if .Values.hub.metrics.serviceMonitor.relabellings }}
      metricRelabelings: {{- toYaml .Values.hub.metrics.serviceMonitor.relabellings | nindent 6 }}
      {{- end }}
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  selector:
    matchLabels: {{- include "common.labels.matchLabels" . | nindent 6 }}
      app.kubernetes.io/component: hub
{{- end }}